url: https://justgetwet.github.io
baseurl: /raining
lang: ja
title: raining all day
description: ただ濡れるだけの人がいる
author: Akira

github: "https://github.com/justgetwet"
twitter: "/"
pinterest: "/"

# remote_theme: justgetwet/raining